/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CurrencyAPMMCCFxRate
 */
public class CurrencyAPMMCCFxRateTest {
    private final CurrencyAPMMCCFxRate model = new CurrencyAPMMCCFxRate();

    /**
     * Model tests for CurrencyAPMMCCFxRate
     */
    @Test
    public void testCurrencyAPMMCCFxRate() {
        // TODO: test CurrencyAPMMCCFxRate
    }

    /**
     * Test the property 'expire'
     */
    @Test
    public void expireTest() {
        // TODO: test expire
    }

    /**
     * Test the property 'sequenceNo'
     */
    @Test
    public void sequenceNoTest() {
        // TODO: test sequenceNo
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'fx'
     */
    @Test
    public void fxTest() {
        // TODO: test fx
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

}
