/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for IppPlan
 */
public class IppPlanTest {
    private final IppPlan model = new IppPlan();

    /**
     * Model tests for IppPlan
     */
    @Test
    public void testIppPlan() {
        // TODO: test IppPlan
    }

    /**
     * Test the property 'sequenceNo'
     */
    @Test
    public void sequenceNoTest() {
        // TODO: test sequenceNo
    }

    /**
     * Test the property 'period'
     */
    @Test
    public void periodTest() {
        // TODO: test period
    }

    /**
     * Test the property 'interestType'
     */
    @Test
    public void interestTypeTest() {
        // TODO: test interestType
    }

    /**
     * Test the property 'interestRate'
     */
    @Test
    public void interestRateTest() {
        // TODO: test interestRate
    }

    /**
     * Test the property 'monthlyAmount'
     */
    @Test
    public void monthlyAmountTest() {
        // TODO: test monthlyAmount
    }

    /**
     * Test the property 'monthlyInterest'
     */
    @Test
    public void monthlyInterestTest() {
        // TODO: test monthlyInterest
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'terms'
     */
    @Test
    public void termsTest() {
        // TODO: test terms
    }

    /**
     * Test the property 'payLaterPeriod'
     */
    @Test
    public void payLaterPeriodTest() {
        // TODO: test payLaterPeriod
    }

}
