/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MerchantConfigurationNotification
 */
public class MerchantConfigurationNotificationTest {
    private final MerchantConfigurationNotification model = new MerchantConfigurationNotification();

    /**
     * Model tests for MerchantConfigurationNotification
     */
    @Test
    public void testMerchantConfigurationNotification() {
        // TODO: test MerchantConfigurationNotification
    }

    /**
     * Test the property 'facebook'
     */
    @Test
    public void facebookTest() {
        // TODO: test facebook
    }

    /**
     * Test the property 'whatsApp'
     */
    @Test
    public void whatsAppTest() {
        // TODO: test whatsApp
    }

    /**
     * Test the property 'line'
     */
    @Test
    public void lineTest() {
        // TODO: test line
    }

}
