/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.MerchantConfigurationPaymentFx;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MerchantConfigurationPayment
 */
public class MerchantConfigurationPaymentTest {
    private final MerchantConfigurationPayment model = new MerchantConfigurationPayment();

    /**
     * Model tests for MerchantConfigurationPayment
     */
    @Test
    public void testMerchantConfigurationPayment() {
        // TODO: test MerchantConfigurationPayment
    }

    /**
     * Test the property 'tokenize'
     */
    @Test
    public void tokenizeTest() {
        // TODO: test tokenize
    }

    /**
     * Test the property 'tokenizeOnly'
     */
    @Test
    public void tokenizeOnlyTest() {
        // TODO: test tokenizeOnly
    }

    /**
     * Test the property 'cardTokenOnly'
     */
    @Test
    public void cardTokenOnlyTest() {
        // TODO: test cardTokenOnly
    }

    /**
     * Test the property 'immediatePayment'
     */
    @Test
    public void immediatePaymentTest() {
        // TODO: test immediatePayment
    }

    /**
     * Test the property 'fx'
     */
    @Test
    public void fxTest() {
        // TODO: test fx
    }

}
