/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BrowserDetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentNotificationRequest
 */
public class PaymentNotificationRequestTest {
    private final PaymentNotificationRequest model = new PaymentNotificationRequest();

    /**
     * Model tests for PaymentNotificationRequest
     */
    @Test
    public void testPaymentNotificationRequest() {
        // TODO: test PaymentNotificationRequest
    }

    /**
     * Test the property 'plateform'
     */
    @Test
    public void plateformTest() {
        // TODO: test plateform
    }

    /**
     * Test the property 'recipientID'
     */
    @Test
    public void recipientIDTest() {
        // TODO: test recipientID
    }

    /**
     * Test the property 'recipientName'
     */
    @Test
    public void recipientNameTest() {
        // TODO: test recipientName
    }

    /**
     * Test the property 'paymentToken'
     */
    @Test
    public void paymentTokenTest() {
        // TODO: test paymentToken
    }

    /**
     * Test the property 'locale'
     */
    @Test
    public void localeTest() {
        // TODO: test locale
    }

    /**
     * Test the property 'clientID'
     */
    @Test
    public void clientIDTest() {
        // TODO: test clientID
    }

    /**
     * Test the property 'browserDetails'
     */
    @Test
    public void browserDetailsTest() {
        // TODO: test browserDetails
    }

}
