/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentOptionDetailsValidationCardType
 */
public class PaymentOptionDetailsValidationCardTypeTest {
    private final PaymentOptionDetailsValidationCardType model = new PaymentOptionDetailsValidationCardType();

    /**
     * Model tests for PaymentOptionDetailsValidationCardType
     */
    @Test
    public void testPaymentOptionDetailsValidationCardType() {
        // TODO: test PaymentOptionDetailsValidationCardType
    }

    /**
     * Test the property 'sequenceNo'
     */
    @Test
    public void sequenceNoTest() {
        // TODO: test sequenceNo
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'prefixes'
     */
    @Test
    public void prefixesTest() {
        // TODO: test prefixes
    }

    /**
     * Test the property 'regex'
     */
    @Test
    public void regexTest() {
        // TODO: test regex
    }

    /**
     * Test the property 'iconUrl'
     */
    @Test
    public void iconUrlTest() {
        // TODO: test iconUrl
    }

}
