/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentOptionDetailsCustomData
 */
public class PaymentOptionDetailsCustomDataTest {
    private final PaymentOptionDetailsCustomData model = new PaymentOptionDetailsCustomData();

    /**
     * Model tests for PaymentOptionDetailsCustomData
     */
    @Test
    public void testPaymentOptionDetailsCustomData() {
        // TODO: test PaymentOptionDetailsCustomData
    }

    /**
     * Test the property 'sequenceNo'
     */
    @Test
    public void sequenceNoTest() {
        // TODO: test sequenceNo
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
