/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PodInfoProviderMerchantDetails;
import com.konfigthis.client.model.PodInfoProviderTransactionDetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentOptionDetailsInfoProvider
 */
public class PaymentOptionDetailsInfoProviderTest {
    private final PaymentOptionDetailsInfoProvider model = new PaymentOptionDetailsInfoProvider();

    /**
     * Model tests for PaymentOptionDetailsInfoProvider
     */
    @Test
    public void testPaymentOptionDetailsInfoProvider() {
        // TODO: test PaymentOptionDetailsInfoProvider
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'channels'
     */
    @Test
    public void channelsTest() {
        // TODO: test channels
    }

    /**
     * Test the property 'merchantDetails'
     */
    @Test
    public void merchantDetailsTest() {
        // TODO: test merchantDetails
    }

    /**
     * Test the property 'transactionDetails'
     */
    @Test
    public void transactionDetailsTest() {
        // TODO: test transactionDetails
    }

    /**
     * Test the property 'terms'
     */
    @Test
    public void termsTest() {
        // TODO: test terms
    }

    /**
     * Test the property 'termsConsent'
     */
    @Test
    public void termsConsentTest() {
        // TODO: test termsConsent
    }

}
