/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.MerchantConfiguration;
import com.konfigthis.client.model.PaymentOptionDetailsChannel;
import com.konfigthis.client.model.PaymentOptionDetailsValidation;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentOptionDetailsResponse
 */
public class PaymentOptionDetailsResponseTest {
    private final PaymentOptionDetailsResponse model = new PaymentOptionDetailsResponse();

    /**
     * Model tests for PaymentOptionDetailsResponse
     */
    @Test
    public void testPaymentOptionDetailsResponse() {
        // TODO: test PaymentOptionDetailsResponse
    }

    /**
     * Test the property 'totalChannel'
     */
    @Test
    public void totalChannelTest() {
        // TODO: test totalChannel
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'categoryCode'
     */
    @Test
    public void categoryCodeTest() {
        // TODO: test categoryCode
    }

    /**
     * Test the property 'groupCode'
     */
    @Test
    public void groupCodeTest() {
        // TODO: test groupCode
    }

    /**
     * Test the property 'iconUrl'
     */
    @Test
    public void iconUrlTest() {
        // TODO: test iconUrl
    }

    /**
     * Test the property 'channels'
     */
    @Test
    public void channelsTest() {
        // TODO: test channels
    }

    /**
     * Test the property 'validation'
     */
    @Test
    public void validationTest() {
        // TODO: test validation
    }

    /**
     * Test the property '_configuration'
     */
    @Test
    public void _configurationTest() {
        // TODO: test _configuration
    }

    /**
     * Test the property 'respCode'
     */
    @Test
    public void respCodeTest() {
        // TODO: test respCode
    }

    /**
     * Test the property 'respDesc'
     */
    @Test
    public void respDescTest() {
        // TODO: test respDesc
    }

}
