/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentOptionDetailsPaymentCode
 */
public class PaymentOptionDetailsPaymentCodeTest {
    private final PaymentOptionDetailsPaymentCode model = new PaymentOptionDetailsPaymentCode();

    /**
     * Model tests for PaymentOptionDetailsPaymentCode
     */
    @Test
    public void testPaymentOptionDetailsPaymentCode() {
        // TODO: test PaymentOptionDetailsPaymentCode
    }

    /**
     * Test the property 'channelCode'
     */
    @Test
    public void channelCodeTest() {
        // TODO: test channelCode
    }

    /**
     * Test the property 'agentCode'
     */
    @Test
    public void agentCodeTest() {
        // TODO: test agentCode
    }

    /**
     * Test the property 'agentChannelCode'
     */
    @Test
    public void agentChannelCodeTest() {
        // TODO: test agentChannelCode
    }

}
