/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PaymentInitialization;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentInitializationResponse
 */
public class PaymentInitializationResponseTest {
    private final PaymentInitializationResponse model = new PaymentInitializationResponse();

    /**
     * Model tests for PaymentInitializationResponse
     */
    @Test
    public void testPaymentInitializationResponse() {
        // TODO: test PaymentInitializationResponse
    }

    /**
     * Test the property 'initialization'
     */
    @Test
    public void initializationTest() {
        // TODO: test initialization
    }

    /**
     * Test the property 'respCode'
     */
    @Test
    public void respCodeTest() {
        // TODO: test respCode
    }

    /**
     * Test the property 'respDesc'
     */
    @Test
    public void respDescTest() {
        // TODO: test respDesc
    }

}
