/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CreditCardTokenV43;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentCardTokenResponseV43
 */
public class PaymentCardTokenResponseV43Test {
    private final PaymentCardTokenResponseV43 model = new PaymentCardTokenResponseV43();

    /**
     * Model tests for PaymentCardTokenResponseV43
     */
    @Test
    public void testPaymentCardTokenResponseV43() {
        // TODO: test PaymentCardTokenResponseV43
    }

    /**
     * Test the property 'paymentToken'
     */
    @Test
    public void paymentTokenTest() {
        // TODO: test paymentToken
    }

    /**
     * Test the property 'customerToken'
     */
    @Test
    public void customerTokenTest() {
        // TODO: test customerToken
    }

    /**
     * Test the property 'respCode'
     */
    @Test
    public void respCodeTest() {
        // TODO: test respCode
    }

    /**
     * Test the property 'respDesc'
     */
    @Test
    public void respDescTest() {
        // TODO: test respDesc
    }

}
