/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RedirectBackEndPostPaymentRedirectRequest
 */
public class RedirectBackEndPostPaymentRedirectRequestTest {
    private final RedirectBackEndPostPaymentRedirectRequest model = new RedirectBackEndPostPaymentRedirectRequest();

    /**
     * Model tests for RedirectBackEndPostPaymentRedirectRequest
     */
    @Test
    public void testRedirectBackEndPostPaymentRedirectRequest() {
        // TODO: test RedirectBackEndPostPaymentRedirectRequest
    }

    /**
     * Test the property 'paymentResponse'
     */
    @Test
    public void paymentResponseTest() {
        // TODO: test paymentResponse
    }

    /**
     * Test the property 'isLeaveApp'
     */
    @Test
    public void isLeaveAppTest() {
        // TODO: test isLeaveApp
    }

}
