/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TransactionStatusAdditionalInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TransactionStatusResponse
 */
public class TransactionStatusResponseTest {
    private final TransactionStatusResponse model = new TransactionStatusResponse();

    /**
     * Model tests for TransactionStatusResponse
     */
    @Test
    public void testTransactionStatusResponse() {
        // TODO: test TransactionStatusResponse
    }

    /**
     * Test the property 'locale'
     */
    @Test
    public void localeTest() {
        // TODO: test locale
    }

    /**
     * Test the property 'additionalInfo'
     */
    @Test
    public void additionalInfoTest() {
        // TODO: test additionalInfo
    }

    /**
     * Test the property 'invoiceNo'
     */
    @Test
    public void invoiceNoTest() {
        // TODO: test invoiceNo
    }

    /**
     * Test the property 'channelCode'
     */
    @Test
    public void channelCodeTest() {
        // TODO: test channelCode
    }

    /**
     * Test the property 'respCode'
     */
    @Test
    public void respCodeTest() {
        // TODO: test respCode
    }

    /**
     * Test the property 'respDesc'
     */
    @Test
    public void respDescTest() {
        // TODO: test respDesc
    }

}
