/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TransactionStatusRewards;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TransactionStatusLoyaltyInfo
 */
public class TransactionStatusLoyaltyInfoTest {
    private final TransactionStatusLoyaltyInfo model = new TransactionStatusLoyaltyInfo();

    /**
     * Model tests for TransactionStatusLoyaltyInfo
     */
    @Test
    public void testTransactionStatusLoyaltyInfo() {
        // TODO: test TransactionStatusLoyaltyInfo
    }

    /**
     * Test the property 'paymentScheme'
     */
    @Test
    public void paymentSchemeTest() {
        // TODO: test paymentScheme
    }

    /**
     * Test the property 'redeemAmount'
     */
    @Test
    public void redeemAmountTest() {
        // TODO: test redeemAmount
    }

    /**
     * Test the property 'rewards'
     */
    @Test
    public void rewardsTest() {
        // TODO: test rewards
    }

}
