/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TransactionStatusInfo;
import com.konfigthis.client.model.TransactionStatusMerchant;
import com.konfigthis.client.model.TransactionStatusPayment;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TransactionStatusAdditionalInfo
 */
public class TransactionStatusAdditionalInfoTest {
    private final TransactionStatusAdditionalInfo model = new TransactionStatusAdditionalInfo();

    /**
     * Model tests for TransactionStatusAdditionalInfo
     */
    @Test
    public void testTransactionStatusAdditionalInfo() {
        // TODO: test TransactionStatusAdditionalInfo
    }

    /**
     * Test the property 'merchantDetails'
     */
    @Test
    public void merchantDetailsTest() {
        // TODO: test merchantDetails
    }

    /**
     * Test the property 'transactionDetails'
     */
    @Test
    public void transactionDetailsTest() {
        // TODO: test transactionDetails
    }

    /**
     * Test the property 'paymentResultDetails'
     */
    @Test
    public void paymentResultDetailsTest() {
        // TODO: test paymentResultDetails
    }

}
