/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PaymentOptionDetailsPaymentCode
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PaymentOptionDetailsPaymentCode {
  public static final String SERIALIZED_NAME_CHANNEL_CODE = "channelCode";
  @SerializedName(SERIALIZED_NAME_CHANNEL_CODE)
  private String channelCode;

  public static final String SERIALIZED_NAME_AGENT_CODE = "agentCode";
  @SerializedName(SERIALIZED_NAME_AGENT_CODE)
  private String agentCode;

  public static final String SERIALIZED_NAME_AGENT_CHANNEL_CODE = "agentChannelCode";
  @SerializedName(SERIALIZED_NAME_AGENT_CHANNEL_CODE)
  private String agentChannelCode;

  public PaymentOptionDetailsPaymentCode() {
  }

  public PaymentOptionDetailsPaymentCode channelCode(String channelCode) {
    
    
    
    
    this.channelCode = channelCode;
    return this;
  }

   /**
   * Get channelCode
   * @return channelCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getChannelCode() {
    return channelCode;
  }


  public void setChannelCode(String channelCode) {
    
    
    
    this.channelCode = channelCode;
  }


  public PaymentOptionDetailsPaymentCode agentCode(String agentCode) {
    
    
    
    
    this.agentCode = agentCode;
    return this;
  }

   /**
   * Get agentCode
   * @return agentCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAgentCode() {
    return agentCode;
  }


  public void setAgentCode(String agentCode) {
    
    
    
    this.agentCode = agentCode;
  }


  public PaymentOptionDetailsPaymentCode agentChannelCode(String agentChannelCode) {
    
    
    
    
    this.agentChannelCode = agentChannelCode;
    return this;
  }

   /**
   * Get agentChannelCode
   * @return agentChannelCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAgentChannelCode() {
    return agentChannelCode;
  }


  public void setAgentChannelCode(String agentChannelCode) {
    
    
    
    this.agentChannelCode = agentChannelCode;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PaymentOptionDetailsPaymentCode instance itself
   */
  public PaymentOptionDetailsPaymentCode putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentOptionDetailsPaymentCode paymentOptionDetailsPaymentCode = (PaymentOptionDetailsPaymentCode) o;
    return Objects.equals(this.channelCode, paymentOptionDetailsPaymentCode.channelCode) &&
        Objects.equals(this.agentCode, paymentOptionDetailsPaymentCode.agentCode) &&
        Objects.equals(this.agentChannelCode, paymentOptionDetailsPaymentCode.agentChannelCode)&&
        Objects.equals(this.additionalProperties, paymentOptionDetailsPaymentCode.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(channelCode, agentCode, agentChannelCode, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentOptionDetailsPaymentCode {\n");
    sb.append("    channelCode: ").append(toIndentedString(channelCode)).append("\n");
    sb.append("    agentCode: ").append(toIndentedString(agentCode)).append("\n");
    sb.append("    agentChannelCode: ").append(toIndentedString(agentChannelCode)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("channelCode");
    openapiFields.add("agentCode");
    openapiFields.add("agentChannelCode");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PaymentOptionDetailsPaymentCode
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PaymentOptionDetailsPaymentCode.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PaymentOptionDetailsPaymentCode is not found in the empty JSON string", PaymentOptionDetailsPaymentCode.openapiRequiredFields.toString()));
        }
      }
      if (!jsonObj.get("channelCode").isJsonNull() && (jsonObj.get("channelCode") != null && !jsonObj.get("channelCode").isJsonNull()) && !jsonObj.get("channelCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `channelCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("channelCode").toString()));
      }
      if (!jsonObj.get("agentCode").isJsonNull() && (jsonObj.get("agentCode") != null && !jsonObj.get("agentCode").isJsonNull()) && !jsonObj.get("agentCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `agentCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("agentCode").toString()));
      }
      if (!jsonObj.get("agentChannelCode").isJsonNull() && (jsonObj.get("agentChannelCode") != null && !jsonObj.get("agentChannelCode").isJsonNull()) && !jsonObj.get("agentChannelCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `agentChannelCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("agentChannelCode").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PaymentOptionDetailsPaymentCode.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PaymentOptionDetailsPaymentCode' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PaymentOptionDetailsPaymentCode> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PaymentOptionDetailsPaymentCode.class));

       return (TypeAdapter<T>) new TypeAdapter<PaymentOptionDetailsPaymentCode>() {
           @Override
           public void write(JsonWriter out, PaymentOptionDetailsPaymentCode value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PaymentOptionDetailsPaymentCode read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PaymentOptionDetailsPaymentCode instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PaymentOptionDetailsPaymentCode given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PaymentOptionDetailsPaymentCode
  * @throws IOException if the JSON string is invalid with respect to PaymentOptionDetailsPaymentCode
  */
  public static PaymentOptionDetailsPaymentCode fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PaymentOptionDetailsPaymentCode.class);
  }

 /**
  * Convert an instance of PaymentOptionDetailsPaymentCode to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

