/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.MerchantDetails;
import com.konfigthis.client.model.PaymentChannelCategory;
import com.konfigthis.client.model.TransactionDetails;
import com.konfigthis.client.model.UserDetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PaymentOptionResponse
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PaymentOptionResponse {
  public static final String SERIALIZED_NAME_PAYMENT_TOKEN = "paymentToken";
  @SerializedName(SERIALIZED_NAME_PAYMENT_TOKEN)
  private String paymentToken;

  public static final String SERIALIZED_NAME_MERCHANT_DETAILS = "merchantDetails";
  @SerializedName(SERIALIZED_NAME_MERCHANT_DETAILS)
  private MerchantDetails merchantDetails;

  public static final String SERIALIZED_NAME_TRANSACTION_DETAILS = "transactionDetails";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_DETAILS)
  private TransactionDetails transactionDetails;

  public static final String SERIALIZED_NAME_CHANNEL_CATEGORIES = "channelCategories";
  @SerializedName(SERIALIZED_NAME_CHANNEL_CATEGORIES)
  private List<PaymentChannelCategory> channelCategories = null;

  public static final String SERIALIZED_NAME_USER_DETAILS = "userDetails";
  @SerializedName(SERIALIZED_NAME_USER_DETAILS)
  private UserDetails userDetails;

  public static final String SERIALIZED_NAME_RESP_CODE = "respCode";
  @SerializedName(SERIALIZED_NAME_RESP_CODE)
  private String respCode;

  public static final String SERIALIZED_NAME_RESP_DESC = "respDesc";
  @SerializedName(SERIALIZED_NAME_RESP_DESC)
  private String respDesc;

  public PaymentOptionResponse() {
  }

  public PaymentOptionResponse paymentToken(String paymentToken) {
    
    
    
    
    this.paymentToken = paymentToken;
    return this;
  }

   /**
   * Get paymentToken
   * @return paymentToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPaymentToken() {
    return paymentToken;
  }


  public void setPaymentToken(String paymentToken) {
    
    
    
    this.paymentToken = paymentToken;
  }


  public PaymentOptionResponse merchantDetails(MerchantDetails merchantDetails) {
    
    
    
    
    this.merchantDetails = merchantDetails;
    return this;
  }

   /**
   * Get merchantDetails
   * @return merchantDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MerchantDetails getMerchantDetails() {
    return merchantDetails;
  }


  public void setMerchantDetails(MerchantDetails merchantDetails) {
    
    
    
    this.merchantDetails = merchantDetails;
  }


  public PaymentOptionResponse transactionDetails(TransactionDetails transactionDetails) {
    
    
    
    
    this.transactionDetails = transactionDetails;
    return this;
  }

   /**
   * Get transactionDetails
   * @return transactionDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TransactionDetails getTransactionDetails() {
    return transactionDetails;
  }


  public void setTransactionDetails(TransactionDetails transactionDetails) {
    
    
    
    this.transactionDetails = transactionDetails;
  }


  public PaymentOptionResponse channelCategories(List<PaymentChannelCategory> channelCategories) {
    
    
    
    
    this.channelCategories = channelCategories;
    return this;
  }

  public PaymentOptionResponse addChannelCategoriesItem(PaymentChannelCategory channelCategoriesItem) {
    if (this.channelCategories == null) {
      this.channelCategories = new ArrayList<>();
    }
    this.channelCategories.add(channelCategoriesItem);
    return this;
  }

   /**
   * Get channelCategories
   * @return channelCategories
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<PaymentChannelCategory> getChannelCategories() {
    return channelCategories;
  }


  public void setChannelCategories(List<PaymentChannelCategory> channelCategories) {
    
    
    
    this.channelCategories = channelCategories;
  }


  public PaymentOptionResponse userDetails(UserDetails userDetails) {
    
    
    
    
    this.userDetails = userDetails;
    return this;
  }

   /**
   * Get userDetails
   * @return userDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UserDetails getUserDetails() {
    return userDetails;
  }


  public void setUserDetails(UserDetails userDetails) {
    
    
    
    this.userDetails = userDetails;
  }


  public PaymentOptionResponse respCode(String respCode) {
    
    
    
    
    this.respCode = respCode;
    return this;
  }

   /**
   * Get respCode
   * @return respCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRespCode() {
    return respCode;
  }


  public void setRespCode(String respCode) {
    
    
    
    this.respCode = respCode;
  }


  public PaymentOptionResponse respDesc(String respDesc) {
    
    
    
    
    this.respDesc = respDesc;
    return this;
  }

   /**
   * Get respDesc
   * @return respDesc
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRespDesc() {
    return respDesc;
  }


  public void setRespDesc(String respDesc) {
    
    
    
    this.respDesc = respDesc;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PaymentOptionResponse instance itself
   */
  public PaymentOptionResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentOptionResponse paymentOptionResponse = (PaymentOptionResponse) o;
    return Objects.equals(this.paymentToken, paymentOptionResponse.paymentToken) &&
        Objects.equals(this.merchantDetails, paymentOptionResponse.merchantDetails) &&
        Objects.equals(this.transactionDetails, paymentOptionResponse.transactionDetails) &&
        Objects.equals(this.channelCategories, paymentOptionResponse.channelCategories) &&
        Objects.equals(this.userDetails, paymentOptionResponse.userDetails) &&
        Objects.equals(this.respCode, paymentOptionResponse.respCode) &&
        Objects.equals(this.respDesc, paymentOptionResponse.respDesc)&&
        Objects.equals(this.additionalProperties, paymentOptionResponse.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentToken, merchantDetails, transactionDetails, channelCategories, userDetails, respCode, respDesc, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentOptionResponse {\n");
    sb.append("    paymentToken: ").append(toIndentedString(paymentToken)).append("\n");
    sb.append("    merchantDetails: ").append(toIndentedString(merchantDetails)).append("\n");
    sb.append("    transactionDetails: ").append(toIndentedString(transactionDetails)).append("\n");
    sb.append("    channelCategories: ").append(toIndentedString(channelCategories)).append("\n");
    sb.append("    userDetails: ").append(toIndentedString(userDetails)).append("\n");
    sb.append("    respCode: ").append(toIndentedString(respCode)).append("\n");
    sb.append("    respDesc: ").append(toIndentedString(respDesc)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("paymentToken");
    openapiFields.add("merchantDetails");
    openapiFields.add("transactionDetails");
    openapiFields.add("channelCategories");
    openapiFields.add("userDetails");
    openapiFields.add("respCode");
    openapiFields.add("respDesc");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PaymentOptionResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PaymentOptionResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PaymentOptionResponse is not found in the empty JSON string", PaymentOptionResponse.openapiRequiredFields.toString()));
        }
      }
      if (!jsonObj.get("paymentToken").isJsonNull() && (jsonObj.get("paymentToken") != null && !jsonObj.get("paymentToken").isJsonNull()) && !jsonObj.get("paymentToken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `paymentToken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paymentToken").toString()));
      }
      // validate the optional field `merchantDetails`
      if (jsonObj.get("merchantDetails") != null && !jsonObj.get("merchantDetails").isJsonNull()) {
        MerchantDetails.validateJsonObject(jsonObj.getAsJsonObject("merchantDetails"));
      }
      // validate the optional field `transactionDetails`
      if (jsonObj.get("transactionDetails") != null && !jsonObj.get("transactionDetails").isJsonNull()) {
        TransactionDetails.validateJsonObject(jsonObj.getAsJsonObject("transactionDetails"));
      }
      if (jsonObj.get("channelCategories") != null && !jsonObj.get("channelCategories").isJsonNull()) {
        JsonArray jsonArraychannelCategories = jsonObj.getAsJsonArray("channelCategories");
        if (jsonArraychannelCategories != null) {
          // ensure the json data is an array
          if (!jsonObj.get("channelCategories").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `channelCategories` to be an array in the JSON string but got `%s`", jsonObj.get("channelCategories").toString()));
          }

          // validate the optional field `channelCategories` (array)
          for (int i = 0; i < jsonArraychannelCategories.size(); i++) {
            PaymentChannelCategory.validateJsonObject(jsonArraychannelCategories.get(i).getAsJsonObject());
          };
        }
      }
      // validate the optional field `userDetails`
      if (jsonObj.get("userDetails") != null && !jsonObj.get("userDetails").isJsonNull()) {
        UserDetails.validateJsonObject(jsonObj.getAsJsonObject("userDetails"));
      }
      if (!jsonObj.get("respCode").isJsonNull() && (jsonObj.get("respCode") != null && !jsonObj.get("respCode").isJsonNull()) && !jsonObj.get("respCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `respCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("respCode").toString()));
      }
      if (!jsonObj.get("respDesc").isJsonNull() && (jsonObj.get("respDesc") != null && !jsonObj.get("respDesc").isJsonNull()) && !jsonObj.get("respDesc").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `respDesc` to be a primitive type in the JSON string but got `%s`", jsonObj.get("respDesc").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PaymentOptionResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PaymentOptionResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PaymentOptionResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PaymentOptionResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<PaymentOptionResponse>() {
           @Override
           public void write(JsonWriter out, PaymentOptionResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PaymentOptionResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PaymentOptionResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PaymentOptionResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PaymentOptionResponse
  * @throws IOException if the JSON string is invalid with respect to PaymentOptionResponse
  */
  public static PaymentOptionResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PaymentOptionResponse.class);
  }

 /**
  * Convert an instance of PaymentOptionResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

