/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PodInfoProviderMerchantDetails;
import com.konfigthis.client.model.PodInfoProviderTransactionDetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PaymentOptionDetailsInfoProvider
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PaymentOptionDetailsInfoProvider {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_CHANNELS = "channels";
  @SerializedName(SERIALIZED_NAME_CHANNELS)
  private List<String> channels = null;

  public static final String SERIALIZED_NAME_MERCHANT_DETAILS = "merchantDetails";
  @SerializedName(SERIALIZED_NAME_MERCHANT_DETAILS)
  private PodInfoProviderMerchantDetails merchantDetails;

  public static final String SERIALIZED_NAME_TRANSACTION_DETAILS = "transactionDetails";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_DETAILS)
  private PodInfoProviderTransactionDetails transactionDetails;

  public static final String SERIALIZED_NAME_TERMS = "terms";
  @SerializedName(SERIALIZED_NAME_TERMS)
  private String terms;

  public static final String SERIALIZED_NAME_TERMS_CONSENT = "termsConsent";
  @SerializedName(SERIALIZED_NAME_TERMS_CONSENT)
  private Boolean termsConsent;

  public PaymentOptionDetailsInfoProvider() {
  }

  public PaymentOptionDetailsInfoProvider id(String id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    
    
    
    this.id = id;
  }


  public PaymentOptionDetailsInfoProvider channels(List<String> channels) {
    
    
    
    
    this.channels = channels;
    return this;
  }

  public PaymentOptionDetailsInfoProvider addChannelsItem(String channelsItem) {
    if (this.channels == null) {
      this.channels = new ArrayList<>();
    }
    this.channels.add(channelsItem);
    return this;
  }

   /**
   * Get channels
   * @return channels
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getChannels() {
    return channels;
  }


  public void setChannels(List<String> channels) {
    
    
    
    this.channels = channels;
  }


  public PaymentOptionDetailsInfoProvider merchantDetails(PodInfoProviderMerchantDetails merchantDetails) {
    
    
    
    
    this.merchantDetails = merchantDetails;
    return this;
  }

   /**
   * Get merchantDetails
   * @return merchantDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PodInfoProviderMerchantDetails getMerchantDetails() {
    return merchantDetails;
  }


  public void setMerchantDetails(PodInfoProviderMerchantDetails merchantDetails) {
    
    
    
    this.merchantDetails = merchantDetails;
  }


  public PaymentOptionDetailsInfoProvider transactionDetails(PodInfoProviderTransactionDetails transactionDetails) {
    
    
    
    
    this.transactionDetails = transactionDetails;
    return this;
  }

   /**
   * Get transactionDetails
   * @return transactionDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PodInfoProviderTransactionDetails getTransactionDetails() {
    return transactionDetails;
  }


  public void setTransactionDetails(PodInfoProviderTransactionDetails transactionDetails) {
    
    
    
    this.transactionDetails = transactionDetails;
  }


  public PaymentOptionDetailsInfoProvider terms(String terms) {
    
    
    
    
    this.terms = terms;
    return this;
  }

   /**
   * Get terms
   * @return terms
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTerms() {
    return terms;
  }


  public void setTerms(String terms) {
    
    
    
    this.terms = terms;
  }


  public PaymentOptionDetailsInfoProvider termsConsent(Boolean termsConsent) {
    
    
    
    
    this.termsConsent = termsConsent;
    return this;
  }

   /**
   * Get termsConsent
   * @return termsConsent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getTermsConsent() {
    return termsConsent;
  }


  public void setTermsConsent(Boolean termsConsent) {
    
    
    
    this.termsConsent = termsConsent;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PaymentOptionDetailsInfoProvider instance itself
   */
  public PaymentOptionDetailsInfoProvider putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentOptionDetailsInfoProvider paymentOptionDetailsInfoProvider = (PaymentOptionDetailsInfoProvider) o;
    return Objects.equals(this.id, paymentOptionDetailsInfoProvider.id) &&
        Objects.equals(this.channels, paymentOptionDetailsInfoProvider.channels) &&
        Objects.equals(this.merchantDetails, paymentOptionDetailsInfoProvider.merchantDetails) &&
        Objects.equals(this.transactionDetails, paymentOptionDetailsInfoProvider.transactionDetails) &&
        Objects.equals(this.terms, paymentOptionDetailsInfoProvider.terms) &&
        Objects.equals(this.termsConsent, paymentOptionDetailsInfoProvider.termsConsent)&&
        Objects.equals(this.additionalProperties, paymentOptionDetailsInfoProvider.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, channels, merchantDetails, transactionDetails, terms, termsConsent, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentOptionDetailsInfoProvider {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    channels: ").append(toIndentedString(channels)).append("\n");
    sb.append("    merchantDetails: ").append(toIndentedString(merchantDetails)).append("\n");
    sb.append("    transactionDetails: ").append(toIndentedString(transactionDetails)).append("\n");
    sb.append("    terms: ").append(toIndentedString(terms)).append("\n");
    sb.append("    termsConsent: ").append(toIndentedString(termsConsent)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("channels");
    openapiFields.add("merchantDetails");
    openapiFields.add("transactionDetails");
    openapiFields.add("terms");
    openapiFields.add("termsConsent");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PaymentOptionDetailsInfoProvider
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PaymentOptionDetailsInfoProvider.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PaymentOptionDetailsInfoProvider is not found in the empty JSON string", PaymentOptionDetailsInfoProvider.openapiRequiredFields.toString()));
        }
      }
      if (!jsonObj.get("id").isJsonNull() && (jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      // ensure the optional json data is an array if present (nullable)
      if (jsonObj.get("channels") != null && !jsonObj.get("channels").isJsonNull() && !jsonObj.get("channels").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `channels` to be an array in the JSON string or null but got `%s`", jsonObj.get("channels").toString()));
      }
      // validate the optional field `merchantDetails`
      if (jsonObj.get("merchantDetails") != null && !jsonObj.get("merchantDetails").isJsonNull()) {
        PodInfoProviderMerchantDetails.validateJsonObject(jsonObj.getAsJsonObject("merchantDetails"));
      }
      // validate the optional field `transactionDetails`
      if (jsonObj.get("transactionDetails") != null && !jsonObj.get("transactionDetails").isJsonNull()) {
        PodInfoProviderTransactionDetails.validateJsonObject(jsonObj.getAsJsonObject("transactionDetails"));
      }
      if (!jsonObj.get("terms").isJsonNull() && (jsonObj.get("terms") != null && !jsonObj.get("terms").isJsonNull()) && !jsonObj.get("terms").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `terms` to be a primitive type in the JSON string but got `%s`", jsonObj.get("terms").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PaymentOptionDetailsInfoProvider.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PaymentOptionDetailsInfoProvider' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PaymentOptionDetailsInfoProvider> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PaymentOptionDetailsInfoProvider.class));

       return (TypeAdapter<T>) new TypeAdapter<PaymentOptionDetailsInfoProvider>() {
           @Override
           public void write(JsonWriter out, PaymentOptionDetailsInfoProvider value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PaymentOptionDetailsInfoProvider read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PaymentOptionDetailsInfoProvider instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PaymentOptionDetailsInfoProvider given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PaymentOptionDetailsInfoProvider
  * @throws IOException if the JSON string is invalid with respect to PaymentOptionDetailsInfoProvider
  */
  public static PaymentOptionDetailsInfoProvider fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PaymentOptionDetailsInfoProvider.class);
  }

 /**
  * Convert an instance of PaymentOptionDetailsInfoProvider to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

