/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PaymentOptionDetailsPayment;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PaymentOptionDetailsChannel
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PaymentOptionDetailsChannel {
  public static final String SERIALIZED_NAME_SEQUENCE_NO = "sequenceNo";
  @SerializedName(SERIALIZED_NAME_SEQUENCE_NO)
  private Integer sequenceNo;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_BANK_SHORT_NAME = "bankShortName";
  @SerializedName(SERIALIZED_NAME_BANK_SHORT_NAME)
  private String bankShortName;

  public static final String SERIALIZED_NAME_CURRENCY_CODES = "currencyCodes";
  @SerializedName(SERIALIZED_NAME_CURRENCY_CODES)
  private List<String> currencyCodes = null;

  public static final String SERIALIZED_NAME_ICON_URL = "iconUrl";
  @SerializedName(SERIALIZED_NAME_ICON_URL)
  private String iconUrl;

  public static final String SERIALIZED_NAME_LOGO_URL = "logoUrl";
  @SerializedName(SERIALIZED_NAME_LOGO_URL)
  private String logoUrl;

  public static final String SERIALIZED_NAME_PAYMENT = "payment";
  @SerializedName(SERIALIZED_NAME_PAYMENT)
  private PaymentOptionDetailsPayment payment;

  public static final String SERIALIZED_NAME_IS_DOWN = "isDown";
  @SerializedName(SERIALIZED_NAME_IS_DOWN)
  private Boolean isDown;

  public static final String SERIALIZED_NAME_CHECK_ELIGIBLE_OPTION = "checkEligibleOption";
  @SerializedName(SERIALIZED_NAME_CHECK_ELIGIBLE_OPTION)
  private Boolean checkEligibleOption;

  public static final String SERIALIZED_NAME_IPP_PROVIDER_CODE = "ippProviderCode";
  @SerializedName(SERIALIZED_NAME_IPP_PROVIDER_CODE)
  private String ippProviderCode;

  public static final String SERIALIZED_NAME_REGISTRATION_STATUS = "registrationStatus";
  @SerializedName(SERIALIZED_NAME_REGISTRATION_STATUS)
  private String registrationStatus;

  public static final String SERIALIZED_NAME_PARTNER_MERCHANT_REF_I_D = "partnerMerchantRefID";
  @SerializedName(SERIALIZED_NAME_PARTNER_MERCHANT_REF_I_D)
  private String partnerMerchantRefID;

  public PaymentOptionDetailsChannel() {
  }

  public PaymentOptionDetailsChannel sequenceNo(Integer sequenceNo) {
    
    
    
    
    this.sequenceNo = sequenceNo;
    return this;
  }

   /**
   * Get sequenceNo
   * @return sequenceNo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getSequenceNo() {
    return sequenceNo;
  }


  public void setSequenceNo(Integer sequenceNo) {
    
    
    
    this.sequenceNo = sequenceNo;
  }


  public PaymentOptionDetailsChannel name(String name) {
    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    
    this.name = name;
  }


  public PaymentOptionDetailsChannel bankShortName(String bankShortName) {
    
    
    
    
    this.bankShortName = bankShortName;
    return this;
  }

   /**
   * Get bankShortName
   * @return bankShortName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBankShortName() {
    return bankShortName;
  }


  public void setBankShortName(String bankShortName) {
    
    
    
    this.bankShortName = bankShortName;
  }


  public PaymentOptionDetailsChannel currencyCodes(List<String> currencyCodes) {
    
    
    
    
    this.currencyCodes = currencyCodes;
    return this;
  }

  public PaymentOptionDetailsChannel addCurrencyCodesItem(String currencyCodesItem) {
    if (this.currencyCodes == null) {
      this.currencyCodes = new ArrayList<>();
    }
    this.currencyCodes.add(currencyCodesItem);
    return this;
  }

   /**
   * Get currencyCodes
   * @return currencyCodes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getCurrencyCodes() {
    return currencyCodes;
  }


  public void setCurrencyCodes(List<String> currencyCodes) {
    
    
    
    this.currencyCodes = currencyCodes;
  }


  public PaymentOptionDetailsChannel iconUrl(String iconUrl) {
    
    
    
    
    this.iconUrl = iconUrl;
    return this;
  }

   /**
   * Get iconUrl
   * @return iconUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIconUrl() {
    return iconUrl;
  }


  public void setIconUrl(String iconUrl) {
    
    
    
    this.iconUrl = iconUrl;
  }


  public PaymentOptionDetailsChannel logoUrl(String logoUrl) {
    
    
    
    
    this.logoUrl = logoUrl;
    return this;
  }

   /**
   * Get logoUrl
   * @return logoUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLogoUrl() {
    return logoUrl;
  }


  public void setLogoUrl(String logoUrl) {
    
    
    
    this.logoUrl = logoUrl;
  }


  public PaymentOptionDetailsChannel payment(PaymentOptionDetailsPayment payment) {
    
    
    
    
    this.payment = payment;
    return this;
  }

   /**
   * Get payment
   * @return payment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PaymentOptionDetailsPayment getPayment() {
    return payment;
  }


  public void setPayment(PaymentOptionDetailsPayment payment) {
    
    
    
    this.payment = payment;
  }


  public PaymentOptionDetailsChannel isDown(Boolean isDown) {
    
    
    
    
    this.isDown = isDown;
    return this;
  }

   /**
   * Get isDown
   * @return isDown
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsDown() {
    return isDown;
  }


  public void setIsDown(Boolean isDown) {
    
    
    
    this.isDown = isDown;
  }


  public PaymentOptionDetailsChannel checkEligibleOption(Boolean checkEligibleOption) {
    
    
    
    
    this.checkEligibleOption = checkEligibleOption;
    return this;
  }

   /**
   * Get checkEligibleOption
   * @return checkEligibleOption
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getCheckEligibleOption() {
    return checkEligibleOption;
  }


  public void setCheckEligibleOption(Boolean checkEligibleOption) {
    
    
    
    this.checkEligibleOption = checkEligibleOption;
  }


  public PaymentOptionDetailsChannel ippProviderCode(String ippProviderCode) {
    
    
    
    
    this.ippProviderCode = ippProviderCode;
    return this;
  }

   /**
   * Get ippProviderCode
   * @return ippProviderCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIppProviderCode() {
    return ippProviderCode;
  }


  public void setIppProviderCode(String ippProviderCode) {
    
    
    
    this.ippProviderCode = ippProviderCode;
  }


  public PaymentOptionDetailsChannel registrationStatus(String registrationStatus) {
    
    
    
    
    this.registrationStatus = registrationStatus;
    return this;
  }

   /**
   * Get registrationStatus
   * @return registrationStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRegistrationStatus() {
    return registrationStatus;
  }


  public void setRegistrationStatus(String registrationStatus) {
    
    
    
    this.registrationStatus = registrationStatus;
  }


  public PaymentOptionDetailsChannel partnerMerchantRefID(String partnerMerchantRefID) {
    
    
    
    
    this.partnerMerchantRefID = partnerMerchantRefID;
    return this;
  }

   /**
   * Get partnerMerchantRefID
   * @return partnerMerchantRefID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPartnerMerchantRefID() {
    return partnerMerchantRefID;
  }


  public void setPartnerMerchantRefID(String partnerMerchantRefID) {
    
    
    
    this.partnerMerchantRefID = partnerMerchantRefID;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PaymentOptionDetailsChannel instance itself
   */
  public PaymentOptionDetailsChannel putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentOptionDetailsChannel paymentOptionDetailsChannel = (PaymentOptionDetailsChannel) o;
    return Objects.equals(this.sequenceNo, paymentOptionDetailsChannel.sequenceNo) &&
        Objects.equals(this.name, paymentOptionDetailsChannel.name) &&
        Objects.equals(this.bankShortName, paymentOptionDetailsChannel.bankShortName) &&
        Objects.equals(this.currencyCodes, paymentOptionDetailsChannel.currencyCodes) &&
        Objects.equals(this.iconUrl, paymentOptionDetailsChannel.iconUrl) &&
        Objects.equals(this.logoUrl, paymentOptionDetailsChannel.logoUrl) &&
        Objects.equals(this.payment, paymentOptionDetailsChannel.payment) &&
        Objects.equals(this.isDown, paymentOptionDetailsChannel.isDown) &&
        Objects.equals(this.checkEligibleOption, paymentOptionDetailsChannel.checkEligibleOption) &&
        Objects.equals(this.ippProviderCode, paymentOptionDetailsChannel.ippProviderCode) &&
        Objects.equals(this.registrationStatus, paymentOptionDetailsChannel.registrationStatus) &&
        Objects.equals(this.partnerMerchantRefID, paymentOptionDetailsChannel.partnerMerchantRefID)&&
        Objects.equals(this.additionalProperties, paymentOptionDetailsChannel.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(sequenceNo, name, bankShortName, currencyCodes, iconUrl, logoUrl, payment, isDown, checkEligibleOption, ippProviderCode, registrationStatus, partnerMerchantRefID, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentOptionDetailsChannel {\n");
    sb.append("    sequenceNo: ").append(toIndentedString(sequenceNo)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    bankShortName: ").append(toIndentedString(bankShortName)).append("\n");
    sb.append("    currencyCodes: ").append(toIndentedString(currencyCodes)).append("\n");
    sb.append("    iconUrl: ").append(toIndentedString(iconUrl)).append("\n");
    sb.append("    logoUrl: ").append(toIndentedString(logoUrl)).append("\n");
    sb.append("    payment: ").append(toIndentedString(payment)).append("\n");
    sb.append("    isDown: ").append(toIndentedString(isDown)).append("\n");
    sb.append("    checkEligibleOption: ").append(toIndentedString(checkEligibleOption)).append("\n");
    sb.append("    ippProviderCode: ").append(toIndentedString(ippProviderCode)).append("\n");
    sb.append("    registrationStatus: ").append(toIndentedString(registrationStatus)).append("\n");
    sb.append("    partnerMerchantRefID: ").append(toIndentedString(partnerMerchantRefID)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("sequenceNo");
    openapiFields.add("name");
    openapiFields.add("bankShortName");
    openapiFields.add("currencyCodes");
    openapiFields.add("iconUrl");
    openapiFields.add("logoUrl");
    openapiFields.add("payment");
    openapiFields.add("isDown");
    openapiFields.add("checkEligibleOption");
    openapiFields.add("ippProviderCode");
    openapiFields.add("registrationStatus");
    openapiFields.add("partnerMerchantRefID");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PaymentOptionDetailsChannel
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PaymentOptionDetailsChannel.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PaymentOptionDetailsChannel is not found in the empty JSON string", PaymentOptionDetailsChannel.openapiRequiredFields.toString()));
        }
      }
      if (!jsonObj.get("name").isJsonNull() && (jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("bankShortName").isJsonNull() && (jsonObj.get("bankShortName") != null && !jsonObj.get("bankShortName").isJsonNull()) && !jsonObj.get("bankShortName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `bankShortName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bankShortName").toString()));
      }
      // ensure the optional json data is an array if present (nullable)
      if (jsonObj.get("currencyCodes") != null && !jsonObj.get("currencyCodes").isJsonNull() && !jsonObj.get("currencyCodes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `currencyCodes` to be an array in the JSON string or null but got `%s`", jsonObj.get("currencyCodes").toString()));
      }
      if (!jsonObj.get("iconUrl").isJsonNull() && (jsonObj.get("iconUrl") != null && !jsonObj.get("iconUrl").isJsonNull()) && !jsonObj.get("iconUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `iconUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("iconUrl").toString()));
      }
      if (!jsonObj.get("logoUrl").isJsonNull() && (jsonObj.get("logoUrl") != null && !jsonObj.get("logoUrl").isJsonNull()) && !jsonObj.get("logoUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `logoUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("logoUrl").toString()));
      }
      // validate the optional field `payment`
      if (jsonObj.get("payment") != null && !jsonObj.get("payment").isJsonNull()) {
        PaymentOptionDetailsPayment.validateJsonObject(jsonObj.getAsJsonObject("payment"));
      }
      if (!jsonObj.get("ippProviderCode").isJsonNull() && (jsonObj.get("ippProviderCode") != null && !jsonObj.get("ippProviderCode").isJsonNull()) && !jsonObj.get("ippProviderCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ippProviderCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ippProviderCode").toString()));
      }
      if (!jsonObj.get("registrationStatus").isJsonNull() && (jsonObj.get("registrationStatus") != null && !jsonObj.get("registrationStatus").isJsonNull()) && !jsonObj.get("registrationStatus").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `registrationStatus` to be a primitive type in the JSON string but got `%s`", jsonObj.get("registrationStatus").toString()));
      }
      if (!jsonObj.get("partnerMerchantRefID").isJsonNull() && (jsonObj.get("partnerMerchantRefID") != null && !jsonObj.get("partnerMerchantRefID").isJsonNull()) && !jsonObj.get("partnerMerchantRefID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `partnerMerchantRefID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("partnerMerchantRefID").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PaymentOptionDetailsChannel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PaymentOptionDetailsChannel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PaymentOptionDetailsChannel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PaymentOptionDetailsChannel.class));

       return (TypeAdapter<T>) new TypeAdapter<PaymentOptionDetailsChannel>() {
           @Override
           public void write(JsonWriter out, PaymentOptionDetailsChannel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PaymentOptionDetailsChannel read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PaymentOptionDetailsChannel instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PaymentOptionDetailsChannel given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PaymentOptionDetailsChannel
  * @throws IOException if the JSON string is invalid with respect to PaymentOptionDetailsChannel
  */
  public static PaymentOptionDetailsChannel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PaymentOptionDetailsChannel.class);
  }

 /**
  * Convert an instance of PaymentOptionDetailsChannel to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

