/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PaymentLoyaltyReward;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PaymentLoyaltyPointInfoResponse
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PaymentLoyaltyPointInfoResponse {
  public static final String SERIALIZED_NAME_PAYMENT_TOKEN = "paymentToken";
  @SerializedName(SERIALIZED_NAME_PAYMENT_TOKEN)
  private String paymentToken;

  public static final String SERIALIZED_NAME_PROVIDER_I_D = "providerID";
  @SerializedName(SERIALIZED_NAME_PROVIDER_I_D)
  private String providerID;

  public static final String SERIALIZED_NAME_PROVIDER_NAME = "providerName";
  @SerializedName(SERIALIZED_NAME_PROVIDER_NAME)
  private String providerName;

  public static final String SERIALIZED_NAME_REFERENCE_I_D = "referenceID";
  @SerializedName(SERIALIZED_NAME_REFERENCE_I_D)
  private String referenceID;

  public static final String SERIALIZED_NAME_PROVIDER_TYPE = "providerType";
  @SerializedName(SERIALIZED_NAME_PROVIDER_TYPE)
  private String providerType;

  public static final String SERIALIZED_NAME_TERMS = "terms";
  @SerializedName(SERIALIZED_NAME_TERMS)
  private String terms;

  public static final String SERIALIZED_NAME_REWARDS = "rewards";
  @SerializedName(SERIALIZED_NAME_REWARDS)
  private List<PaymentLoyaltyReward> rewards = null;

  public static final String SERIALIZED_NAME_RESP_CODE = "respCode";
  @SerializedName(SERIALIZED_NAME_RESP_CODE)
  private String respCode;

  public static final String SERIALIZED_NAME_RESP_DESC = "respDesc";
  @SerializedName(SERIALIZED_NAME_RESP_DESC)
  private String respDesc;

  public PaymentLoyaltyPointInfoResponse() {
  }

  public PaymentLoyaltyPointInfoResponse paymentToken(String paymentToken) {
    
    
    
    
    this.paymentToken = paymentToken;
    return this;
  }

   /**
   * Get paymentToken
   * @return paymentToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPaymentToken() {
    return paymentToken;
  }


  public void setPaymentToken(String paymentToken) {
    
    
    
    this.paymentToken = paymentToken;
  }


  public PaymentLoyaltyPointInfoResponse providerID(String providerID) {
    
    
    
    
    this.providerID = providerID;
    return this;
  }

   /**
   * Get providerID
   * @return providerID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getProviderID() {
    return providerID;
  }


  public void setProviderID(String providerID) {
    
    
    
    this.providerID = providerID;
  }


  public PaymentLoyaltyPointInfoResponse providerName(String providerName) {
    
    
    
    
    this.providerName = providerName;
    return this;
  }

   /**
   * Get providerName
   * @return providerName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getProviderName() {
    return providerName;
  }


  public void setProviderName(String providerName) {
    
    
    
    this.providerName = providerName;
  }


  public PaymentLoyaltyPointInfoResponse referenceID(String referenceID) {
    
    
    
    
    this.referenceID = referenceID;
    return this;
  }

   /**
   * Get referenceID
   * @return referenceID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getReferenceID() {
    return referenceID;
  }


  public void setReferenceID(String referenceID) {
    
    
    
    this.referenceID = referenceID;
  }


  public PaymentLoyaltyPointInfoResponse providerType(String providerType) {
    
    
    
    
    this.providerType = providerType;
    return this;
  }

   /**
   * Get providerType
   * @return providerType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getProviderType() {
    return providerType;
  }


  public void setProviderType(String providerType) {
    
    
    
    this.providerType = providerType;
  }


  public PaymentLoyaltyPointInfoResponse terms(String terms) {
    
    
    
    
    this.terms = terms;
    return this;
  }

   /**
   * Get terms
   * @return terms
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTerms() {
    return terms;
  }


  public void setTerms(String terms) {
    
    
    
    this.terms = terms;
  }


  public PaymentLoyaltyPointInfoResponse rewards(List<PaymentLoyaltyReward> rewards) {
    
    
    
    
    this.rewards = rewards;
    return this;
  }

  public PaymentLoyaltyPointInfoResponse addRewardsItem(PaymentLoyaltyReward rewardsItem) {
    if (this.rewards == null) {
      this.rewards = new ArrayList<>();
    }
    this.rewards.add(rewardsItem);
    return this;
  }

   /**
   * Get rewards
   * @return rewards
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<PaymentLoyaltyReward> getRewards() {
    return rewards;
  }


  public void setRewards(List<PaymentLoyaltyReward> rewards) {
    
    
    
    this.rewards = rewards;
  }


  public PaymentLoyaltyPointInfoResponse respCode(String respCode) {
    
    
    
    
    this.respCode = respCode;
    return this;
  }

   /**
   * Get respCode
   * @return respCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRespCode() {
    return respCode;
  }


  public void setRespCode(String respCode) {
    
    
    
    this.respCode = respCode;
  }


  public PaymentLoyaltyPointInfoResponse respDesc(String respDesc) {
    
    
    
    
    this.respDesc = respDesc;
    return this;
  }

   /**
   * Get respDesc
   * @return respDesc
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRespDesc() {
    return respDesc;
  }


  public void setRespDesc(String respDesc) {
    
    
    
    this.respDesc = respDesc;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PaymentLoyaltyPointInfoResponse instance itself
   */
  public PaymentLoyaltyPointInfoResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentLoyaltyPointInfoResponse paymentLoyaltyPointInfoResponse = (PaymentLoyaltyPointInfoResponse) o;
    return Objects.equals(this.paymentToken, paymentLoyaltyPointInfoResponse.paymentToken) &&
        Objects.equals(this.providerID, paymentLoyaltyPointInfoResponse.providerID) &&
        Objects.equals(this.providerName, paymentLoyaltyPointInfoResponse.providerName) &&
        Objects.equals(this.referenceID, paymentLoyaltyPointInfoResponse.referenceID) &&
        Objects.equals(this.providerType, paymentLoyaltyPointInfoResponse.providerType) &&
        Objects.equals(this.terms, paymentLoyaltyPointInfoResponse.terms) &&
        Objects.equals(this.rewards, paymentLoyaltyPointInfoResponse.rewards) &&
        Objects.equals(this.respCode, paymentLoyaltyPointInfoResponse.respCode) &&
        Objects.equals(this.respDesc, paymentLoyaltyPointInfoResponse.respDesc)&&
        Objects.equals(this.additionalProperties, paymentLoyaltyPointInfoResponse.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentToken, providerID, providerName, referenceID, providerType, terms, rewards, respCode, respDesc, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentLoyaltyPointInfoResponse {\n");
    sb.append("    paymentToken: ").append(toIndentedString(paymentToken)).append("\n");
    sb.append("    providerID: ").append(toIndentedString(providerID)).append("\n");
    sb.append("    providerName: ").append(toIndentedString(providerName)).append("\n");
    sb.append("    referenceID: ").append(toIndentedString(referenceID)).append("\n");
    sb.append("    providerType: ").append(toIndentedString(providerType)).append("\n");
    sb.append("    terms: ").append(toIndentedString(terms)).append("\n");
    sb.append("    rewards: ").append(toIndentedString(rewards)).append("\n");
    sb.append("    respCode: ").append(toIndentedString(respCode)).append("\n");
    sb.append("    respDesc: ").append(toIndentedString(respDesc)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("paymentToken");
    openapiFields.add("providerID");
    openapiFields.add("providerName");
    openapiFields.add("referenceID");
    openapiFields.add("providerType");
    openapiFields.add("terms");
    openapiFields.add("rewards");
    openapiFields.add("respCode");
    openapiFields.add("respDesc");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PaymentLoyaltyPointInfoResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PaymentLoyaltyPointInfoResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PaymentLoyaltyPointInfoResponse is not found in the empty JSON string", PaymentLoyaltyPointInfoResponse.openapiRequiredFields.toString()));
        }
      }
      if (!jsonObj.get("paymentToken").isJsonNull() && (jsonObj.get("paymentToken") != null && !jsonObj.get("paymentToken").isJsonNull()) && !jsonObj.get("paymentToken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `paymentToken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paymentToken").toString()));
      }
      if (!jsonObj.get("providerID").isJsonNull() && (jsonObj.get("providerID") != null && !jsonObj.get("providerID").isJsonNull()) && !jsonObj.get("providerID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `providerID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("providerID").toString()));
      }
      if (!jsonObj.get("providerName").isJsonNull() && (jsonObj.get("providerName") != null && !jsonObj.get("providerName").isJsonNull()) && !jsonObj.get("providerName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `providerName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("providerName").toString()));
      }
      if (!jsonObj.get("referenceID").isJsonNull() && (jsonObj.get("referenceID") != null && !jsonObj.get("referenceID").isJsonNull()) && !jsonObj.get("referenceID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `referenceID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("referenceID").toString()));
      }
      if (!jsonObj.get("providerType").isJsonNull() && (jsonObj.get("providerType") != null && !jsonObj.get("providerType").isJsonNull()) && !jsonObj.get("providerType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `providerType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("providerType").toString()));
      }
      if (!jsonObj.get("terms").isJsonNull() && (jsonObj.get("terms") != null && !jsonObj.get("terms").isJsonNull()) && !jsonObj.get("terms").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `terms` to be a primitive type in the JSON string but got `%s`", jsonObj.get("terms").toString()));
      }
      if (jsonObj.get("rewards") != null && !jsonObj.get("rewards").isJsonNull()) {
        JsonArray jsonArrayrewards = jsonObj.getAsJsonArray("rewards");
        if (jsonArrayrewards != null) {
          // ensure the json data is an array
          if (!jsonObj.get("rewards").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `rewards` to be an array in the JSON string but got `%s`", jsonObj.get("rewards").toString()));
          }

          // validate the optional field `rewards` (array)
          for (int i = 0; i < jsonArrayrewards.size(); i++) {
            PaymentLoyaltyReward.validateJsonObject(jsonArrayrewards.get(i).getAsJsonObject());
          };
        }
      }
      if (!jsonObj.get("respCode").isJsonNull() && (jsonObj.get("respCode") != null && !jsonObj.get("respCode").isJsonNull()) && !jsonObj.get("respCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `respCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("respCode").toString()));
      }
      if (!jsonObj.get("respDesc").isJsonNull() && (jsonObj.get("respDesc") != null && !jsonObj.get("respDesc").isJsonNull()) && !jsonObj.get("respDesc").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `respDesc` to be a primitive type in the JSON string but got `%s`", jsonObj.get("respDesc").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PaymentLoyaltyPointInfoResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PaymentLoyaltyPointInfoResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PaymentLoyaltyPointInfoResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PaymentLoyaltyPointInfoResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<PaymentLoyaltyPointInfoResponse>() {
           @Override
           public void write(JsonWriter out, PaymentLoyaltyPointInfoResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PaymentLoyaltyPointInfoResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PaymentLoyaltyPointInfoResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PaymentLoyaltyPointInfoResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PaymentLoyaltyPointInfoResponse
  * @throws IOException if the JSON string is invalid with respect to PaymentLoyaltyPointInfoResponse
  */
  public static PaymentLoyaltyPointInfoResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PaymentLoyaltyPointInfoResponse.class);
  }

 /**
  * Convert an instance of PaymentLoyaltyPointInfoResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

