/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BrowserDetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PaymentNotificationRequest
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PaymentNotificationRequest {
  public static final String SERIALIZED_NAME_PLATEFORM = "plateform";
  @SerializedName(SERIALIZED_NAME_PLATEFORM)
  private String plateform;

  public static final String SERIALIZED_NAME_RECIPIENT_I_D = "recipientID";
  @SerializedName(SERIALIZED_NAME_RECIPIENT_I_D)
  private String recipientID;

  public static final String SERIALIZED_NAME_RECIPIENT_NAME = "recipientName";
  @SerializedName(SERIALIZED_NAME_RECIPIENT_NAME)
  private String recipientName;

  public static final String SERIALIZED_NAME_PAYMENT_TOKEN = "paymentToken";
  @SerializedName(SERIALIZED_NAME_PAYMENT_TOKEN)
  private String paymentToken;

  public static final String SERIALIZED_NAME_LOCALE = "locale";
  @SerializedName(SERIALIZED_NAME_LOCALE)
  private String locale;

  public static final String SERIALIZED_NAME_CLIENT_I_D = "clientID";
  @SerializedName(SERIALIZED_NAME_CLIENT_I_D)
  private UUID clientID;

  public static final String SERIALIZED_NAME_BROWSER_DETAILS = "browserDetails";
  @SerializedName(SERIALIZED_NAME_BROWSER_DETAILS)
  private BrowserDetails browserDetails;

  public PaymentNotificationRequest() {
  }

  public PaymentNotificationRequest plateform(String plateform) {
    
    
    
    
    this.plateform = plateform;
    return this;
  }

   /**
   * Get plateform
   * @return plateform
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPlateform() {
    return plateform;
  }


  public void setPlateform(String plateform) {
    
    
    
    this.plateform = plateform;
  }


  public PaymentNotificationRequest recipientID(String recipientID) {
    
    
    
    
    this.recipientID = recipientID;
    return this;
  }

   /**
   * Get recipientID
   * @return recipientID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRecipientID() {
    return recipientID;
  }


  public void setRecipientID(String recipientID) {
    
    
    
    this.recipientID = recipientID;
  }


  public PaymentNotificationRequest recipientName(String recipientName) {
    
    
    
    
    this.recipientName = recipientName;
    return this;
  }

   /**
   * Get recipientName
   * @return recipientName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRecipientName() {
    return recipientName;
  }


  public void setRecipientName(String recipientName) {
    
    
    
    this.recipientName = recipientName;
  }


  public PaymentNotificationRequest paymentToken(String paymentToken) {
    
    
    
    
    this.paymentToken = paymentToken;
    return this;
  }

   /**
   * Get paymentToken
   * @return paymentToken
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getPaymentToken() {
    return paymentToken;
  }


  public void setPaymentToken(String paymentToken) {
    
    
    
    this.paymentToken = paymentToken;
  }


  public PaymentNotificationRequest locale(String locale) {
    
    
    
    
    this.locale = locale;
    return this;
  }

   /**
   * Get locale
   * @return locale
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLocale() {
    return locale;
  }


  public void setLocale(String locale) {
    
    
    
    this.locale = locale;
  }


  public PaymentNotificationRequest clientID(UUID clientID) {
    
    
    
    
    this.clientID = clientID;
    return this;
  }

   /**
   * Get clientID
   * @return clientID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UUID getClientID() {
    return clientID;
  }


  public void setClientID(UUID clientID) {
    
    
    
    this.clientID = clientID;
  }


  public PaymentNotificationRequest browserDetails(BrowserDetails browserDetails) {
    
    
    
    
    this.browserDetails = browserDetails;
    return this;
  }

   /**
   * Get browserDetails
   * @return browserDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BrowserDetails getBrowserDetails() {
    return browserDetails;
  }


  public void setBrowserDetails(BrowserDetails browserDetails) {
    
    
    
    this.browserDetails = browserDetails;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PaymentNotificationRequest instance itself
   */
  public PaymentNotificationRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentNotificationRequest paymentNotificationRequest = (PaymentNotificationRequest) o;
    return Objects.equals(this.plateform, paymentNotificationRequest.plateform) &&
        Objects.equals(this.recipientID, paymentNotificationRequest.recipientID) &&
        Objects.equals(this.recipientName, paymentNotificationRequest.recipientName) &&
        Objects.equals(this.paymentToken, paymentNotificationRequest.paymentToken) &&
        Objects.equals(this.locale, paymentNotificationRequest.locale) &&
        Objects.equals(this.clientID, paymentNotificationRequest.clientID) &&
        Objects.equals(this.browserDetails, paymentNotificationRequest.browserDetails)&&
        Objects.equals(this.additionalProperties, paymentNotificationRequest.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(plateform, recipientID, recipientName, paymentToken, locale, clientID, browserDetails, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentNotificationRequest {\n");
    sb.append("    plateform: ").append(toIndentedString(plateform)).append("\n");
    sb.append("    recipientID: ").append(toIndentedString(recipientID)).append("\n");
    sb.append("    recipientName: ").append(toIndentedString(recipientName)).append("\n");
    sb.append("    paymentToken: ").append(toIndentedString(paymentToken)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    clientID: ").append(toIndentedString(clientID)).append("\n");
    sb.append("    browserDetails: ").append(toIndentedString(browserDetails)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("plateform");
    openapiFields.add("recipientID");
    openapiFields.add("recipientName");
    openapiFields.add("paymentToken");
    openapiFields.add("locale");
    openapiFields.add("clientID");
    openapiFields.add("browserDetails");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("paymentToken");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PaymentNotificationRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PaymentNotificationRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PaymentNotificationRequest is not found in the empty JSON string", PaymentNotificationRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PaymentNotificationRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("plateform").isJsonNull() && (jsonObj.get("plateform") != null && !jsonObj.get("plateform").isJsonNull()) && !jsonObj.get("plateform").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `plateform` to be a primitive type in the JSON string but got `%s`", jsonObj.get("plateform").toString()));
      }
      if (!jsonObj.get("recipientID").isJsonNull() && (jsonObj.get("recipientID") != null && !jsonObj.get("recipientID").isJsonNull()) && !jsonObj.get("recipientID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `recipientID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("recipientID").toString()));
      }
      if (!jsonObj.get("recipientName").isJsonNull() && (jsonObj.get("recipientName") != null && !jsonObj.get("recipientName").isJsonNull()) && !jsonObj.get("recipientName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `recipientName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("recipientName").toString()));
      }
      if (!jsonObj.get("paymentToken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `paymentToken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paymentToken").toString()));
      }
      if (!jsonObj.get("locale").isJsonNull() && (jsonObj.get("locale") != null && !jsonObj.get("locale").isJsonNull()) && !jsonObj.get("locale").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `locale` to be a primitive type in the JSON string but got `%s`", jsonObj.get("locale").toString()));
      }
      if ((jsonObj.get("clientID") != null && !jsonObj.get("clientID").isJsonNull()) && !jsonObj.get("clientID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `clientID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("clientID").toString()));
      }
      // validate the optional field `browserDetails`
      if (jsonObj.get("browserDetails") != null && !jsonObj.get("browserDetails").isJsonNull()) {
        BrowserDetails.validateJsonObject(jsonObj.getAsJsonObject("browserDetails"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PaymentNotificationRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PaymentNotificationRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PaymentNotificationRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PaymentNotificationRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<PaymentNotificationRequest>() {
           @Override
           public void write(JsonWriter out, PaymentNotificationRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PaymentNotificationRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PaymentNotificationRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PaymentNotificationRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PaymentNotificationRequest
  * @throws IOException if the JSON string is invalid with respect to PaymentNotificationRequest
  */
  public static PaymentNotificationRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PaymentNotificationRequest.class);
  }

 /**
  * Convert an instance of PaymentNotificationRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

