/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Recurring
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class Recurring {
  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private String amount;

  public static final String SERIALIZED_NAME_INTERVAL = "interval";
  @SerializedName(SERIALIZED_NAME_INTERVAL)
  private Integer interval;

  public static final String SERIALIZED_NAME_COUNT = "count";
  @SerializedName(SERIALIZED_NAME_COUNT)
  private Integer count;

  public static final String SERIALIZED_NAME_CHARGE_NEXT_DATE = "chargeNextDate";
  @SerializedName(SERIALIZED_NAME_CHARGE_NEXT_DATE)
  private String chargeNextDate;

  public static final String SERIALIZED_NAME_CHARGE_ON_DATE = "chargeOnDate";
  @SerializedName(SERIALIZED_NAME_CHARGE_ON_DATE)
  private String chargeOnDate;

  public Recurring() {
  }

  public Recurring amount(String amount) {
    
    
    
    
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAmount() {
    return amount;
  }


  public void setAmount(String amount) {
    
    
    
    this.amount = amount;
  }


  public Recurring interval(Integer interval) {
    
    
    
    
    this.interval = interval;
    return this;
  }

   /**
   * Get interval
   * @return interval
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getInterval() {
    return interval;
  }


  public void setInterval(Integer interval) {
    
    
    
    this.interval = interval;
  }


  public Recurring count(Integer count) {
    
    
    
    
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getCount() {
    return count;
  }


  public void setCount(Integer count) {
    
    
    
    this.count = count;
  }


  public Recurring chargeNextDate(String chargeNextDate) {
    
    
    
    
    this.chargeNextDate = chargeNextDate;
    return this;
  }

   /**
   * Get chargeNextDate
   * @return chargeNextDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getChargeNextDate() {
    return chargeNextDate;
  }


  public void setChargeNextDate(String chargeNextDate) {
    
    
    
    this.chargeNextDate = chargeNextDate;
  }


  public Recurring chargeOnDate(String chargeOnDate) {
    
    
    
    
    this.chargeOnDate = chargeOnDate;
    return this;
  }

   /**
   * Get chargeOnDate
   * @return chargeOnDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getChargeOnDate() {
    return chargeOnDate;
  }


  public void setChargeOnDate(String chargeOnDate) {
    
    
    
    this.chargeOnDate = chargeOnDate;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the Recurring instance itself
   */
  public Recurring putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Recurring recurring = (Recurring) o;
    return Objects.equals(this.amount, recurring.amount) &&
        Objects.equals(this.interval, recurring.interval) &&
        Objects.equals(this.count, recurring.count) &&
        Objects.equals(this.chargeNextDate, recurring.chargeNextDate) &&
        Objects.equals(this.chargeOnDate, recurring.chargeOnDate)&&
        Objects.equals(this.additionalProperties, recurring.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, interval, count, chargeNextDate, chargeOnDate, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Recurring {\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    interval: ").append(toIndentedString(interval)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    chargeNextDate: ").append(toIndentedString(chargeNextDate)).append("\n");
    sb.append("    chargeOnDate: ").append(toIndentedString(chargeOnDate)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("amount");
    openapiFields.add("interval");
    openapiFields.add("count");
    openapiFields.add("chargeNextDate");
    openapiFields.add("chargeOnDate");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Recurring
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!Recurring.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Recurring is not found in the empty JSON string", Recurring.openapiRequiredFields.toString()));
        }
      }
      if (!jsonObj.get("amount").isJsonNull() && (jsonObj.get("amount") != null && !jsonObj.get("amount").isJsonNull()) && !jsonObj.get("amount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `amount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("amount").toString()));
      }
      if (!jsonObj.get("chargeNextDate").isJsonNull() && (jsonObj.get("chargeNextDate") != null && !jsonObj.get("chargeNextDate").isJsonNull()) && !jsonObj.get("chargeNextDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `chargeNextDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("chargeNextDate").toString()));
      }
      if (!jsonObj.get("chargeOnDate").isJsonNull() && (jsonObj.get("chargeOnDate") != null && !jsonObj.get("chargeOnDate").isJsonNull()) && !jsonObj.get("chargeOnDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `chargeOnDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("chargeOnDate").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Recurring.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Recurring' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Recurring> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Recurring.class));

       return (TypeAdapter<T>) new TypeAdapter<Recurring>() {
           @Override
           public void write(JsonWriter out, Recurring value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public Recurring read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             Recurring instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Recurring given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Recurring
  * @throws IOException if the JSON string is invalid with respect to Recurring
  */
  public static Recurring fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Recurring.class);
  }

 /**
  * Convert an instance of Recurring to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

