/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * RedirectFrontEndPostPaymentRedirectRequest
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class RedirectFrontEndPostPaymentRedirectRequest {
  public static final String SERIALIZED_NAME_PAY_RESPONSE = "payResponse";
  @SerializedName(SERIALIZED_NAME_PAY_RESPONSE)
  private String payResponse;

  public static final String SERIALIZED_NAME_IS_LEAVE_APP = "isLeaveApp";
  @SerializedName(SERIALIZED_NAME_IS_LEAVE_APP)
  private String isLeaveApp;

  public RedirectFrontEndPostPaymentRedirectRequest() {
  }

  public RedirectFrontEndPostPaymentRedirectRequest payResponse(String payResponse) {
    
    
    
    
    this.payResponse = payResponse;
    return this;
  }

   /**
   * Get payResponse
   * @return payResponse
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPayResponse() {
    return payResponse;
  }


  public void setPayResponse(String payResponse) {
    
    
    
    this.payResponse = payResponse;
  }


  public RedirectFrontEndPostPaymentRedirectRequest isLeaveApp(String isLeaveApp) {
    
    
    
    
    this.isLeaveApp = isLeaveApp;
    return this;
  }

   /**
   * Get isLeaveApp
   * @return isLeaveApp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIsLeaveApp() {
    return isLeaveApp;
  }


  public void setIsLeaveApp(String isLeaveApp) {
    
    
    
    this.isLeaveApp = isLeaveApp;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the RedirectFrontEndPostPaymentRedirectRequest instance itself
   */
  public RedirectFrontEndPostPaymentRedirectRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RedirectFrontEndPostPaymentRedirectRequest redirectFrontEndPostPaymentRedirectRequest = (RedirectFrontEndPostPaymentRedirectRequest) o;
    return Objects.equals(this.payResponse, redirectFrontEndPostPaymentRedirectRequest.payResponse) &&
        Objects.equals(this.isLeaveApp, redirectFrontEndPostPaymentRedirectRequest.isLeaveApp)&&
        Objects.equals(this.additionalProperties, redirectFrontEndPostPaymentRedirectRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payResponse, isLeaveApp, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RedirectFrontEndPostPaymentRedirectRequest {\n");
    sb.append("    payResponse: ").append(toIndentedString(payResponse)).append("\n");
    sb.append("    isLeaveApp: ").append(toIndentedString(isLeaveApp)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("payResponse");
    openapiFields.add("isLeaveApp");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to RedirectFrontEndPostPaymentRedirectRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!RedirectFrontEndPostPaymentRedirectRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RedirectFrontEndPostPaymentRedirectRequest is not found in the empty JSON string", RedirectFrontEndPostPaymentRedirectRequest.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("payResponse") != null && !jsonObj.get("payResponse").isJsonNull()) && !jsonObj.get("payResponse").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `payResponse` to be a primitive type in the JSON string but got `%s`", jsonObj.get("payResponse").toString()));
      }
      if ((jsonObj.get("isLeaveApp") != null && !jsonObj.get("isLeaveApp").isJsonNull()) && !jsonObj.get("isLeaveApp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `isLeaveApp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("isLeaveApp").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RedirectFrontEndPostPaymentRedirectRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RedirectFrontEndPostPaymentRedirectRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RedirectFrontEndPostPaymentRedirectRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RedirectFrontEndPostPaymentRedirectRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<RedirectFrontEndPostPaymentRedirectRequest>() {
           @Override
           public void write(JsonWriter out, RedirectFrontEndPostPaymentRedirectRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public RedirectFrontEndPostPaymentRedirectRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             RedirectFrontEndPostPaymentRedirectRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of RedirectFrontEndPostPaymentRedirectRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RedirectFrontEndPostPaymentRedirectRequest
  * @throws IOException if the JSON string is invalid with respect to RedirectFrontEndPostPaymentRedirectRequest
  */
  public static RedirectFrontEndPostPaymentRedirectRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RedirectFrontEndPostPaymentRedirectRequest.class);
  }

 /**
  * Convert an instance of RedirectFrontEndPostPaymentRedirectRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

