/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.BrowserDetails;
import com.konfigthis.client.model.PayloadRequest;
import com.konfigthis.client.model.PaymentApmMccExchangeRateResponse;
import com.konfigthis.client.model.PaymentBaseRequest;
import com.konfigthis.client.model.PaymentExchangeRateConverterRequest;
import com.konfigthis.client.model.PaymentExchangeRateConverterResponse;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ExchangeRateApi
 */
@Disabled
public class ExchangeRateApiTest {

    private static ExchangeRateApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ExchangeRateApi(apiClient);
    }

    /**
     * APM MCC Exchange Rate
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apmMccTest() throws ApiException {
        String paymentToken = null;
        String locale = null;
        UUID clientID = null;
        BrowserDetails browserDetails = null;
        PaymentApmMccExchangeRateResponse response = api.apmMcc(paymentToken)
                .locale(locale)
                .clientID(clientID)
                .browserDetails(browserDetails)
                .execute();
        // TODO: test validations
    }

    /**
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRateTest() throws ApiException {
        String paymentToken = null;
        String bin = null;
        String locale = null;
        UUID clientID = null;
        BrowserDetails browserDetails = null;
        PaymentExchangeRateConverterResponse response = api.getRate(paymentToken)
                .bin(bin)
                .locale(locale)
                .clientID(clientID)
                .browserDetails(browserDetails)
                .execute();
        // TODO: test validations
    }

    /**
     * JWT Request Endpoint
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void requestEndpointTest() throws ApiException {
        String payload = null;
        PayloadRequest response = api.requestEndpoint()
                .payload(payload)
                .execute();
        // TODO: test validations
    }

}
