/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.RedirectBackEndPostPaymentRedirectRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RedirectBackEndApi
 */
@Disabled
public class RedirectBackEndApiTest {

    private static RedirectBackEndApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new RedirectBackEndApi(apiClient);
    }

    /**
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postPaymentRedirectTest() throws ApiException {
        String paymentResponse = null;
        String isLeaveApp = null;
        api.postPaymentRedirect()
                .paymentResponse(paymentResponse)
                .isLeaveApp(isLeaveApp)
                .execute();
        // TODO: test validations
    }

}
