/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.BrowserDetails;
import com.konfigthis.client.model.CardInstallmentPlanInfoRequest;
import com.konfigthis.client.model.PaymentOptionDetailsResponse;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class CardInstallmentPlanInfoApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public CardInstallmentPlanInfoApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public CardInstallmentPlanInfoApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call createCall(CardInstallmentPlanInfoRequest cardInstallmentPlanInfoRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = cardInstallmentPlanInfoRequest;

        // create path and map variables
        String localVarPath = "/payment/4.3/cardinstallmentplaninfo";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json",
            "text/json",
            "text/plain"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json",
            "text/json",
            "application/json-patch+json",
            "application/*+json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createValidateBeforeCall(CardInstallmentPlanInfoRequest cardInstallmentPlanInfoRequest, final ApiCallback _callback) throws ApiException {
        return createCall(cardInstallmentPlanInfoRequest, _callback);

    }


    private ApiResponse<PaymentOptionDetailsResponse> createWithHttpInfo(CardInstallmentPlanInfoRequest cardInstallmentPlanInfoRequest) throws ApiException {
        okhttp3.Call localVarCall = createValidateBeforeCall(cardInstallmentPlanInfoRequest, null);
        Type localVarReturnType = new TypeToken<PaymentOptionDetailsResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call createAsync(CardInstallmentPlanInfoRequest cardInstallmentPlanInfoRequest, final ApiCallback<PaymentOptionDetailsResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = createValidateBeforeCall(cardInstallmentPlanInfoRequest, _callback);
        Type localVarReturnType = new TypeToken<PaymentOptionDetailsResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class CreateRequestBuilder {
        private final String paymentToken;
        private String cardNo;
        private String bankCode;
        private String locale;
        private UUID clientID;
        private BrowserDetails browserDetails;

        private CreateRequestBuilder(String paymentToken) {
            this.paymentToken = paymentToken;
        }

        /**
         * Set cardNo
         * @param cardNo  (optional)
         * @return CreateRequestBuilder
         */
        public CreateRequestBuilder cardNo(String cardNo) {
            this.cardNo = cardNo;
            return this;
        }
        
        /**
         * Set bankCode
         * @param bankCode  (optional)
         * @return CreateRequestBuilder
         */
        public CreateRequestBuilder bankCode(String bankCode) {
            this.bankCode = bankCode;
            return this;
        }
        
        /**
         * Set locale
         * @param locale  (optional)
         * @return CreateRequestBuilder
         */
        public CreateRequestBuilder locale(String locale) {
            this.locale = locale;
            return this;
        }
        
        /**
         * Set clientID
         * @param clientID  (optional)
         * @return CreateRequestBuilder
         */
        public CreateRequestBuilder clientID(UUID clientID) {
            this.clientID = clientID;
            return this;
        }
        
        /**
         * Set browserDetails
         * @param browserDetails  (optional)
         * @return CreateRequestBuilder
         */
        public CreateRequestBuilder browserDetails(BrowserDetails browserDetails) {
            this.browserDetails = browserDetails;
            return this;
        }
        
        /**
         * Build call for create
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            CardInstallmentPlanInfoRequest cardInstallmentPlanInfoRequest = buildBodyParams();
            return createCall(cardInstallmentPlanInfoRequest, _callback);
        }

        private CardInstallmentPlanInfoRequest buildBodyParams() {
            CardInstallmentPlanInfoRequest cardInstallmentPlanInfoRequest = new CardInstallmentPlanInfoRequest();
            cardInstallmentPlanInfoRequest.cardNo(this.cardNo);
            cardInstallmentPlanInfoRequest.bankCode(this.bankCode);
            cardInstallmentPlanInfoRequest.paymentToken(this.paymentToken);
            cardInstallmentPlanInfoRequest.locale(this.locale);
            cardInstallmentPlanInfoRequest.clientID(this.clientID);
            cardInstallmentPlanInfoRequest.browserDetails(this.browserDetails);
            return cardInstallmentPlanInfoRequest;
        }

        /**
         * Execute create request
         * @return PaymentOptionDetailsResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
         </table>
         */
        public PaymentOptionDetailsResponse execute() throws ApiException {
            CardInstallmentPlanInfoRequest cardInstallmentPlanInfoRequest = buildBodyParams();
            ApiResponse<PaymentOptionDetailsResponse> localVarResp = createWithHttpInfo(cardInstallmentPlanInfoRequest);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute create request with HTTP info returned
         * @return ApiResponse&lt;PaymentOptionDetailsResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<PaymentOptionDetailsResponse> executeWithHttpInfo() throws ApiException {
            CardInstallmentPlanInfoRequest cardInstallmentPlanInfoRequest = buildBodyParams();
            return createWithHttpInfo(cardInstallmentPlanInfoRequest);
        }

        /**
         * Execute create request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<PaymentOptionDetailsResponse> _callback) throws ApiException {
            CardInstallmentPlanInfoRequest cardInstallmentPlanInfoRequest = buildBodyParams();
            return createAsync(cardInstallmentPlanInfoRequest, _callback);
        }
    }

    /**
     * 
     * 
     * @return CreateRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public CreateRequestBuilder create(String paymentToken) throws IllegalArgumentException {
        if (paymentToken == null) throw new IllegalArgumentException("\"paymentToken\" is required but got null");
            

        return new CreateRequestBuilder(paymentToken);
    }
}
