/*
 * PGW Payment API 4.3
 * Rest API for PGW payment purpose - LATEST
 *
 * The version of the OpenAPI document: 4.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.BrowserDetails;
import com.konfigthis.client.model.TransactionStatusRequest;
import com.konfigthis.client.model.TransactionStatusResponse;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class TransactionStatusApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public TransactionStatusApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public TransactionStatusApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call updateTransactionStatusCall(TransactionStatusRequest transactionStatusRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = transactionStatusRequest;

        // create path and map variables
        String localVarPath = "/payment/4.3/transactionstatus";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json",
            "text/json",
            "text/plain"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json",
            "text/json",
            "application/json-patch+json",
            "application/*+json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateTransactionStatusValidateBeforeCall(TransactionStatusRequest transactionStatusRequest, final ApiCallback _callback) throws ApiException {
        return updateTransactionStatusCall(transactionStatusRequest, _callback);

    }


    private ApiResponse<TransactionStatusResponse> updateTransactionStatusWithHttpInfo(TransactionStatusRequest transactionStatusRequest) throws ApiException {
        okhttp3.Call localVarCall = updateTransactionStatusValidateBeforeCall(transactionStatusRequest, null);
        Type localVarReturnType = new TypeToken<TransactionStatusResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call updateTransactionStatusAsync(TransactionStatusRequest transactionStatusRequest, final ApiCallback<TransactionStatusResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateTransactionStatusValidateBeforeCall(transactionStatusRequest, _callback);
        Type localVarReturnType = new TypeToken<TransactionStatusResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class UpdateTransactionStatusRequestBuilder {
        private final String paymentToken;
        private Boolean additionalInfo;
        private String locale;
        private UUID clientID;
        private BrowserDetails browserDetails;

        private UpdateTransactionStatusRequestBuilder(String paymentToken) {
            this.paymentToken = paymentToken;
        }

        /**
         * Set additionalInfo
         * @param additionalInfo  (optional)
         * @return UpdateTransactionStatusRequestBuilder
         */
        public UpdateTransactionStatusRequestBuilder additionalInfo(Boolean additionalInfo) {
            this.additionalInfo = additionalInfo;
            return this;
        }
        
        /**
         * Set locale
         * @param locale  (optional)
         * @return UpdateTransactionStatusRequestBuilder
         */
        public UpdateTransactionStatusRequestBuilder locale(String locale) {
            this.locale = locale;
            return this;
        }
        
        /**
         * Set clientID
         * @param clientID  (optional)
         * @return UpdateTransactionStatusRequestBuilder
         */
        public UpdateTransactionStatusRequestBuilder clientID(UUID clientID) {
            this.clientID = clientID;
            return this;
        }
        
        /**
         * Set browserDetails
         * @param browserDetails  (optional)
         * @return UpdateTransactionStatusRequestBuilder
         */
        public UpdateTransactionStatusRequestBuilder browserDetails(BrowserDetails browserDetails) {
            this.browserDetails = browserDetails;
            return this;
        }
        
        /**
         * Build call for updateTransactionStatus
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            TransactionStatusRequest transactionStatusRequest = buildBodyParams();
            return updateTransactionStatusCall(transactionStatusRequest, _callback);
        }

        private TransactionStatusRequest buildBodyParams() {
            TransactionStatusRequest transactionStatusRequest = new TransactionStatusRequest();
            transactionStatusRequest.additionalInfo(this.additionalInfo);
            transactionStatusRequest.paymentToken(this.paymentToken);
            transactionStatusRequest.locale(this.locale);
            transactionStatusRequest.clientID(this.clientID);
            transactionStatusRequest.browserDetails(this.browserDetails);
            return transactionStatusRequest;
        }

        /**
         * Execute updateTransactionStatus request
         * @return TransactionStatusResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
         </table>
         */
        public TransactionStatusResponse execute() throws ApiException {
            TransactionStatusRequest transactionStatusRequest = buildBodyParams();
            ApiResponse<TransactionStatusResponse> localVarResp = updateTransactionStatusWithHttpInfo(transactionStatusRequest);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute updateTransactionStatus request with HTTP info returned
         * @return ApiResponse&lt;TransactionStatusResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<TransactionStatusResponse> executeWithHttpInfo() throws ApiException {
            TransactionStatusRequest transactionStatusRequest = buildBodyParams();
            return updateTransactionStatusWithHttpInfo(transactionStatusRequest);
        }

        /**
         * Execute updateTransactionStatus request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<TransactionStatusResponse> _callback) throws ApiException {
            TransactionStatusRequest transactionStatusRequest = buildBodyParams();
            return updateTransactionStatusAsync(transactionStatusRequest, _callback);
        }
    }

    /**
     * 
     * 
     * @return UpdateTransactionStatusRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public UpdateTransactionStatusRequestBuilder updateTransactionStatus(String paymentToken) throws IllegalArgumentException {
        if (paymentToken == null) throw new IllegalArgumentException("\"paymentToken\" is required but got null");
            

        return new UpdateTransactionStatusRequestBuilder(paymentToken);
    }
}
